from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from app.models.jobs import JobEnvelope, JobState, QueuedJob
from app.models.resume import ResumeDocument, RewriteTarget


@dataclass(slots=True)
class PresignedUpload:
    upload_url: str
    object_key: str
    method: str = "PUT"
    headers: dict[str, str] | None = None


class ObjectStore(Protocol):
    def create_presigned_upload(self, object_key: str, content_type: str) -> PresignedUpload: ...
    def put_json(self, object_key: str, data: dict) -> None: ...
    def get_json(self, object_key: str) -> dict: ...
    def put_bytes(self, object_key: str, content: bytes) -> None: ...
    def get_bytes(self, object_key: str) -> bytes: ...
    def exists(self, object_key: str) -> bool: ...
    def delete(self, object_key: str) -> None: ...


class QueueService(Protocol):
    def send(self, envelope: JobEnvelope) -> None: ...
    def receive(self, max_messages: int = 1) -> list[QueuedJob]: ...
    def acknowledge(self, job: QueuedJob) -> None: ...


class JobStateStore(Protocol):
    def create(self, state: JobState) -> None: ...
    def get(self, job_id: str) -> JobState: ...
    def save(self, state: JobState) -> None: ...


class ResumeParser(Protocol):
    def parse(self, source_bytes: bytes, filename: str = "", *, ai_provider: str | None = None, ai_model: str | None = None, ai_api_key: str | None = None) -> ResumeDocument: ...


class ResumeTailor(Protocol):
    def tailor(self, document: ResumeDocument, *, mode: str, context: dict[str, str | None], ai_provider: str | None = None, ai_model: str | None = None, ai_api_key: str | None = None) -> ResumeDocument: ...
    def rewrite_text(self, text: str, *, instruction: str, mode: str, ai_provider: str | None = None, ai_model: str | None = None, ai_api_key: str | None = None) -> str: ...
    def apply_rewrites(self, document: ResumeDocument, targets: list[RewriteTarget], ai_provider: str | None = None, ai_model: str | None = None, ai_api_key: str | None = None) -> ResumeDocument: ...


class DocumentRenderer(Protocol):
    def render(self, document: ResumeDocument, *, template_id: str) -> bytes: ...
